name: love_link_app
description: A modern love-themed Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  lottie: ^2.2.0
  shared_preferences: ^2.3.3  #^2.1.1
  flutter_lints: ^5.0.0
  file_picker: ^5.0.0
  table_calendar: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/heart_animation.json
    - assets/default_avatar.png
